In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
for i in range(0,3):
    for j in range(0,3):
        x[i][j]= 2*x[i][j]

print(x)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [5]:
data={
    'product_name':['p1','p2','p3'],
    'price':[40,20,90],
    'stock_quantity':[20,50,90]
}

df = pd.DataFrame(data)

print(df)

  product_name  price  stock_quantity
0           p1     40              20
1           p2     20              50
2           p3     90              90


In [8]:
filter = df[df['stock_quantity']>50]
print(filter)

  product_name  price  stock_quantity
2           p3     90              90
